name: "LFD"
on:
  workflow_dispatch:
  schedule:
    - cron: "37 11,17,23 * * 4"

jobs:
  get_lfd:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: local::.

    - name: Obtain and plot LFD testing data
      run: |
        Rscript 'inst/scripts/lfd_education.r'
        Rscript 'inst/scripts/lfd_ltla.r'

    - name: Commit files
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - LFD"
        git add --all
        git diff-index --quiet HEAD || git commit -m "LFD - weekly"
        git push
